### PR TITLE
Removed couple of attributes from StakeInfo

### PR DESCRIPTION
**Pull request by ksridharbabuus**
Removed couple of attributes stakeIndex and stakedAmount from StakeInfo structure based on the review comments.

### CODE REVIEW

**Comment by astroseger** [comment]
1. I would propose to have only two amounts in ```StakeInfo```: ```pendingForApprovalAmount``` and ```approvedAmount```. We don’t need the third amount because tokens are either approved or not. In the current contract the semantic of ```amount``` is not clear (what is it? only the sum of ```pendingForApprovalAmount``` and ```approvedAmount```).  It will also simplify all functions where we have interplay between these three values because we have to support and check consistency of two identical sources of information.

2. I propose to remove the following requirement:
``` now <= stakeMap[currentStakeMapIndex].endPeriod``` from ```allowRequestForClaim``` modifier. Contract should be resistant to the situation in which the operator never creates a new window after the expiration of the old one. But with this requirement funds will be locked forever in this situation. 

3. I would propose to rename ```allowRequestForClaim``` change to ```stopAutoRenewal``` which is better reflect its functionality. 

4. Why is there a requirement ```stakeMap[stakeMapIndex].stakeHolderInfo[msg.sender].status == StakeStatus.Approved``` in allowRequestForClaim? Actually the semantic of StakeStatus.Approved is not clear. It can be that part of stake is already approved (auto renewed part) and part of the stake is not approved.

5. I would propose to remove status from ```StakeInfo```. If we have only two amounts in StakeInfo (```pendingForApprovalAmount``` and ```approvedAmount```) then everything is clear from these amounts, and status only creates two sources of information, consistency of which we have to support. Moreover we don’t really need to know why ```approvedAmount``` is zero either it was ```Claimed``` or ```Renewed``` (and “moved” to the next window).

6. I think that ```totalStake``` and ```tokenBalance``` have misleading names (at least for me). I would propose to rename ```tokenBalance``` into ```tokenTotalApprovedStake``` and ```totalStake``` into ```tokenBalance```. 



7. It seems that ```autoRenewStake``` and ```renewStake``` have very similar functionality. Could we try to separate common functionality into a helper function?

8. Probably users would like to call ```claimStake``` immediately after ```requestForClaim``` (which I’ve previously proposed to rename to ```stopAutoRenewal```). Should we make special Function to call them both together: ```stopAutoRenewalAndClaimStake```?


9. Am I right that comment before withdrawStake 
```
// To withdraw stake during submission phase
```
is outdated, because with this function staker can also withdraw stakes which were forgotten by the operator.

10. Why do we need the special logic for disable staking operations (```stakingOperationDisabled```)? In order to stop staking, the operator should simply not create a new stake window. I see that  that the operator cannot withdraw tokens if ```stakingOperationDisabled``` is true. But it is the stake operator who set this value. Moreover there is one potentially useful use case for ```stakingOperationDisabled```: to forbid further staking during submission phase (we already ```require(stakingOperationDisabled == false``` in ```allowSubmission```), but in this case it is not logical to forbid withdrawal of tokens. As results I would propose to consider removing ```stakingOperationDisabled``` at all. 

11. We could remove ```nextStakeMapIndex```. We simply should consider the ```currentStakeMapIndex == 0``` as a first “empty” state. 

In openForStake we replace 
```
        require(nextStakeMapIndex == 0 || now > stakeMap[currentStakeMapIndex].approvalEndPeriod, "Cannot have more than one stake request at a time");
```
With 
```
      require(currentStakeMapIndex == 0 || now > stakeMap[currentStakeMapIndex].approvalEndPeriod, "Cannot have more than one stake request at a time");
```
we replace:
```
    currentStakeMapIndex = nextStakeMapIndex;
```
 with
```
        currentStakeMapIndex = currentStakeMapIndex + 1;
```
And we replace
``` 
emit OpenForStake(nextStakeMapIndex++, msg.sender, _startPeriod, _endPeriod, _approvalEndPeriod, _windowRewardAmount);
```
With
```
 emit OpenForStake(currentStakeMapIndex - 1, msg.sender, _startPeriod, _endPeriod, _approvalEndPeriod, _windowRewardAmount);
```
Et voila, everything is the same, but we have one variable less in the contract.

12. In ```renewStake``` I propose to rename ```stakeInfo``` variable into ```oldStakeInfo``` variable in order to underline that it is not the current stake info.

**Comment by ksridharbabuus** [comment]
@astroseger 
Please find the updates as per the new PRs:

1. Done. Amount field is used to reduce the computation across the methods. Now we have only two amounts in the refactored contract.
2. No we cannot remove from the requirement. Just to avoid the locking of tokens, we have the disableOperations (which indicates no more staking in the contract). I read the other comment of removing this flag, which is needed for satisfying the certain requirements.
3. Done. Renamed the function. I felt updateAutoRenewal makes more sense than stopAutoRenewal for the current functionality and updated accordingly. 
4. Done. Now we don't have any more status fields.
5. Done. Status field is removed. Instead of checking the global flag we have differentiated the status with the amount fields. In other places it is implemented with additional parameter (for e.g. createStake).
Note: We can even do that using msg.sender check with token Operator but I felt function parameter makes more sense.
6. Done. Existing names seems to be fine as they are indicating their role. Also had additional comments. Any way renamed tokenBalance -> totalApprovedStake and totalStake as is. This seems to be more appropriate than the suggested names.
7. Already there is a helper function doing most of the common code in creating the stake. Intentionally kept the balance updates as per the respective events. Don't want to have another helper function here.
8. Staker cannot make immediately claim after auto renewal update, they need to wait until the endPeriod is completed. 
Note: We cannot ignore the endPeriod check here
9. Done. It was more based on the Status fields, now the refactored contract it was updated as per new logic.
10. We need to have Operation disabled flag to enable the withdrawals for auto renewed stakes. 
11. We can't just replace the currentStakeMapIndex with nextStakeMapIndex. I felt having these two fields is much simpler than doing the calculation of reducing one number in every method where ever we refer current Index. So left the functionality as is.
12. Done. stakeInfo object is only object for existingIndex so there shouldn't be any confusion. Anyway updated the code for both renewStake and autoRenewStake methods.

**Comment by astroseger** [comment]
I think it is a major point so I will do it in a separate comment.
There is still a problem with ```totalApprovedStake``` (it was previously called ```tokenBalance```). I see now that in the current contract it is treated as a “balance of approved tokens”. Sorry that I haven’t seen it in the first review. The problem is as follows: when we start a new stake window ```totalApprovedStake``` will contain amounts from non-autorenewable stakes. It means that ```totalApprovedStake``` will be technically wrong until everybody claims their funds and we don't have restrictions for how long it should take. Consequently, the operator will be able to withdraw more tokens then he really should. 

It also should be noted that we don’t need to track the total amount of tokens into ```TokenStake``` contract since we can get it directly from token contract: ```token.balanceOf(this)```.

My proposition is as following:
* Remove ```totalApprovedStake``` at all since we already have ```windowTotalStake``` in ```StakePeriod``` which is the amount of approved stake in the current stake window.
* Rewrite ```withdrawToken``` functions as following  
```solidity
function withdrawToken(uint256 value) public onlyOperator
    {
        // Restricts withdrawal of stake which are in approval process

        require(token.balanceOf(this).sub(value) >= totalStake.sub(stakeMap[currentStakeMapIndex].windowTotalStake) , "Not enough balance in the contract");
        require(token.transfer(msg.sender, value), "Unable to transfer token to the operator account");

        emit WithdrawToken(tokenOperator, value);
    }
```
We could remove the depositToken function at all because the operator (and everybody else) is able to transfer the tokens to contract directly, but we also can keep it to add transparency.

**Comment by astroseger** [comment]
Two minor points:
1. In my first review, when I proposed to remove nextStakeMapIndex, I made a mistake. There is no need for “doing the calculation of reducing one number”.
 As in my first comment, we simply should consider  the ```currentStakeMapIndex == 0``` as a first “empty” stake window in which non of transactions have been made.

In openForStake we replace: 
```solidity
...
require(nextStakeMapIndex == 0 || now > stakeMap[currentStakeMapIndex].approvalEndPeriod, "Cannot have more than one stake request at a time");
...
 currentStakeMapIndex = nextStakeMapIndex;
...
emit OpenForStake(nextStakeMapIndex++, msg.sender, _startPeriod, _endPeriod, _approvalEndPeriod, _windowRewardAmount);
```
With 
```solidity
require(currentStakeMapIndex == 0 || now > stakeMap[currentStakeMapIndex].approvalEndPeriod, "Cannot have more than one stake request at a time");
...
currentStakeMapIndex = currentStakeMapIndex + 1;
...
emit OpenForStake(currentStakeMapIndex, msg.sender, _startPeriod, _endPeriod, _approvalEndPeriod, _windowRewardAmount);
```

It is cleaner and require less variables with the same amount of calculations (and there is no need for  “doing the calculation of reducing one number”, which I agree would be not nice).

2. Why there is a requirement for non zero amount in ```canUpdateAutoRenewal```, ```allowClaimStake```, ```allowClaimStake``` and ```allowAutoRenewStake``` (and even in ```validStakeLimit```). Technically, it seems, there is no harm in calling functions (in which these modifiers are used) with zero amounts. Of course it would be the waste of gas, but should we protect against it in the contract? I'm not completely sure that we should remove these requirements though (so maybe it is ok to keep it as it is if time is a factor now).

**Comment by ksridharbabuus** [comment]
Here are the changes made for the above to commits:
1. Removed the totalApprovedStake
2. Updated DepositToken & WithdrawToken used by tokenOperator
3. Updated the logic to build the StakeMap Structure, where index zero is dummy with no content.

I still feel we need to have >0 check to avoid unnecessary call to the contract, so left as is.

**Comment by astroseger** [comment]
@ksridharbabuus thank you for patience. 
Only one point. I would propose to rename ```createStake``` to ```_createStake``` or even to ```_create OrUpdateStakeInfo``` (but it is of course optional) .

**Pull request merged**
