### PR TITLE
Staking Enhancements

### PR DESCRIPTION
**Pull request by ksridharbabuus**
Staking Enhancements

### CODE REVIEW

**Comment by astroseger** [comment]
@ksridharbabuus few questions:
1. If manual approval of stakes is removed, then why do we need the notion of approvedAmount and pendingForApprovalAmount? It seems we can have one "amount" instead? 
2. Maybe we can go even further and remove the notion claimableAmount? We could have one "amount" which accumulate all rewards and stakes.
3. We add the current window reward to the WindowTotalStake. But why? Because of it in _calculateRewardAmount we have one extra subtraction (windowRewardAmount should be subtracted from WindowTotalStake)

**Comment by ksridharbabuus** [comment]
@astroseger 
The reason why we haven't went with one Amount is:
1. PendingForApproval will be used to deposit stake or withdraw the stake any number of times during the submission phase. Note that the Submission Phase (1st phase) will be in common with the request for claim (last phase of the window).
2. With claimable functionality user can claim from the current window and they can stake in the new window. Without Claimable array it will be difficult to manage the single Amount field in the common phase of Stake window (Submission & Request for claim phase)
3. Reward is added upfront when the window is opened to simplify the reward calculations during the incubation phase. As you might have noted that total amount will get updated based on the operations. If we don't add during the opening window it will be difficult to manage the reward computation & reward addition to the total stake (reward will be part of new stake) while adding rewards in incubation state. Note that we want to have the reward computation onchain and we got No for offchain calculation.

**Comment by astroseger** [comment]
@ksridharbabuus 
Two major questions:
1. It seems there is noting which force operator to call computeAndAddReward. Operator can open new stake window without calling computeAndAddReward for each staker. Maybe we should consider possibility to design contract in such a way that it is impossible to open new stake window without distributing reward for all stakers (In my draft of staking contract I had counter NStakersNotCalculatedReward). However I agree that operator has a lot of power (for example withdraw all funds from the contract) in any case.

2. In updateAutoRenewal, it seems, it is possible to transfer all approvedAmount into claimable in any time just by specifying old stakeMapIndex. For example if currentStakeMapIndex=2 and user have non-zero approvedAmount then what would happen if user call: updateAutoRenewal(1, False)?  Or is it a desired behavior? 

few minor questions:
1. Operator can change maxDaysToOpenInSecs in any time by calling updateMaxDaysToOpen, so it seems there is no reason for keeping it.  So I would propose to ether remove this functionality completely or to remove updateMaxDaysToOpen function. 
2. I think that updateAutoRenewal is not so good name anymore since there no AutoRenewal flag anymore, and if I understand correctly, all stakes are automatically auto-renewed. I would propose to split this function into two functions: claimFunds and restakeClaimedFunds
3. "mapping (address => uint256) public balances" seems unnecessary since it is not used anywhere. In any case total balances can be calculated from pendingForApprovalAmount, approvedAmount, claimableAmount. So I would propose to consider possibility to remove "balances".
4. "address[] stakeHolders" seems unnecessary since the list of stakers seems to be required only off-chain and we can get it from events. 
5. Total distributed reward could be slightly different from windowRewardAmount because of "div", so it means that windowTotalStake could be slightly different from the actual windowTotalStake (since windowRewardAmount is added to windowTotalStake at once in openForStake).

**Comment by ksridharbabuus** [comment]
@astroseger 
Please find the responses to your questions:
1. Yes, there is a possibility of opening a window with adding the rewards. This we can be considered as a process of running the reward computation and we will be running the scripts to add the rewards. Had a Thought of maintaining the variable to make sure that the rewards are added before opening the new state but unfortunately it is difficult to identify the last reward transaction to indicate the rewards job is completed. Thought of making as part of the offline mandate process to run the rewards job before opening a new window.
Let me know if you have any thoughts of managing the same onchain?
2. No, User cannot opt out from the previous windows. There is a modifier canUpdateAutoRenewal for the method which checks for the optIn/optOut phase.

And for the minor comments:
1. maxDaysToOpenInSecs  - We have added this check as part of the previous comment from Audit to restrict the open of window to futuristic. Left it as in this version as well.
2. Agree, Will change the function name to appropriate name
3. balances is to simplify the front end to get the balance. I feel we can leave it as is.
4. address[] is the standard way of implementation for any mapping fields. Even thou we get from events, this array simplifies of getting the stakers.
5. Yes, That is rounding issue and we cannot avoid it. Will be always in very very few cogs.

**Comment by astroseger** [comment]
> @astroseger
> Please find the responses to your questions:
> 
>     1. Yes, there is a possibility of opening a window with adding the rewards. This we can be considered as a process of running the reward computation and we will be running the scripts to add the rewards. Had a Thought of maintaining the variable to make sure that the rewards are added before opening the new state but unfortunately it is difficult to identify the last reward transaction to indicate the rewards job is completed. Thought of making as part of the offline mandate process to run the rewards job before opening a new window.
>        Let me know if you have any thoughts of managing the same onchain?
> 

We could manage it on-chain by having two counter: NStakers and NStakersWithNotCalculatedReward.
Nstakers is always equal to number of active stakers
NStakersWithNotCalculatedReward is managed in such a way that it is equal to Nstakers at approvalEndPeriod, and it should be 0 at openForStake. I can elaborate more if it is needed. But such on-chain management will cost additional gas.

**Comment by ksridharbabuus** [comment]
@astroseger 
I understand the logic and the computation for this has to be done across all the actions which indeed increases the cost for all the functions. I felt that it is better we make sure that we will add the execution of rewards as mandatory process in offchain. 
Will check the impact of adding this check in the contract. Thanks!

**Comment by ksridharbabuus** [comment]
@astroseger 
Instead of going with the lots of computation of NStaker & NStakersWithNotCalculatedReward, will expose a method to indicate the rewardUpdates for the respective window is completed as shown below sample:
function updateRewardCalcIndex(uint256 stakeMapIndex) public onlyOperator {
// Will add all necessary require conditions as currentStakeMapIndex == stakeMapIndex
rewardComputeIndex = stakeMapIndex;
}
And while opening the window will check for currentStakeMapIndex == rewardComputeIndex 
Where rewardComputeIndex  will be a new variable. This method will be executed after completion & verification of rewardUpdates.
This approach simplifies the calculation thus not increases the gas cost except one additional call that to just to update the index.
Let me know your thoughts. Don't want to add too logic into the contract for the process which needs to be done mandatorily.

**Comment by astroseger** [comment]
> @astroseger
> Instead of going with the lots of computation of NStaker & NStakersWithNotCalculatedReward, will expose a method to indicate the rewardUpdates for the respective window is completed as shown below sample:
> function updateRewardCalcIndex(uint256 stakeMapIndex) public onlyOperator {
> // Will add all necessary require conditions as currentStakeMapIndex == stakeMapIndex
> rewardComputeIndex = stakeMapIndex;
> }
> And while opening the window will check for currentStakeMapIndex == rewardComputeIndex
> Where rewardComputeIndex will be a new variable. This method will be executed after completion & verification of rewardUpdates.
> This approach simplifies the calculation thus not increases the gas cost except one additional call that to just to update the index.
> Let me know your thoughts. Don't want to add too logic into the contract for the process which needs to be done mandatorily.

But Am I right that will not force operator to actual call reward computation for each of stacker?

**Comment by ksridharbabuus** [comment]
@astroseger 
Yes it will not force the Operator to update the rewards for every staker. Since we are going to execute we will make sure that it is executed for all the stakers. This validation is basically will be happening offchain to avoid complex logic on the contract.

**Comment by astroseger** [comment]
> @astroseger
> Yes it will not force the Operator to update the rewards for every staker. Since we are going to execute we will make sure that it is executed for all the stakers. This validation is basically will be happening offchain to avoid complex logic on the contract.

So it is similar to maxDaysToOpenInSecs, it will not prevent operator from doing anything, so I don't think we should add it. If some validation will be done off-chain, it can stay off-chain. Frankly speaking I would propose to remove maxDaysToOpenInSecs also, because in the current form it does not prevent operator from doing anything (because updateMaxDaysToOpen can be called in any moment). But I understand that the external reviewer requested it.

**Comment by astroseger** [comment]
>     5. Yes, That is rounding issue and we cannot avoid it. Will be always in very very few cogs.
The solution would be to not add windowRewardAmount  to the windonTotalStake in openForStake, but add exact reward in computeAndAddReward. But it would probably more gas costly, so I'm not sure we should do it.

**Comment by ksridharbabuus** [comment]
@astroseger 
On Rounding issue, we cannot avoid that will happen in any of the cases. Even during the reward computation the rounding is happening now as well.
We can keep it simple with the existing approach which minimizes the number of computation needed in the contract.

**Comment by ksridharbabuus** [comment]
@astroseger 
Regarding maxDaysToOpenInSecs, yes any time we can increase.
The primary purpose is no to allow too futuristic stake windows by mistake or any chance. I am thinking we can leave as it came as comment in the last review.

**Comment by ksridharbabuus** [comment]
@astroseger 
Did you get a chance to see the reply for confirmation on reward computation before opening of window. The proposed is simple approach than adding a logic with new variables. Thanks!

**Comment by astroseger** [comment]
>     5. Yes, That is rounding issue and we cannot avoid it. Will be always in very very few cogs.
The solution would be to not add windowRewardAmount  to the windonTotalStake in openForStake, but add exact reward in computeAndAddReward. But it would probably more gas costly, so I'm not sure we should do it.

 


> @astroseger
> On Rounding issue, we cannot avoid that will happen in any of the cases. Even during the reward computation the rounding is happening now as well.
> We can keep it simple with the existing approach which minimizes the number of computation needed in the contract.
No exactly. 
In the current contract  after some time windowTotalStake will be slightly different from the sum of all stakes, because of rounding issue in  computeAndAddReward (because sum of distributed rewards will be slightly different from windowTotalStake). But if we add to windowTotalStake the exact value we calculate in  computeAndAddReward then windowTotalStake total stake will be exactly equal to sum of all stakes.

**Comment by astroseger** [comment]
> @astroseger
> Did you get a chance to see the reply for confirmation on reward computation before opening of window. The proposed is simple approach than adding a logic with new variables. Thanks!

Since similar to maxDaysToOpenInSecs this logic is actually do not adds any restrictions to the operator I don't see why we need it.

**Review by raamb — APPROVED** [review]

**Comment by ksridharbabuus** [comment]
Closing this PR as there is another PR from Phase-2 to master with the same code.

**Pull request closed without merging**
